export const urls = {
    reusable: {
        ingame: {
            CSLiveMatchFirst: '',
            CSLiveMatchSecond: '',
            CSUpcomingMatchFirst: '',
            CSUpcomingMatchSecond: '',
            CSFinishedMatchFirst: '',
            CSFinishedMatchSecond: '',
            ValorantLiveMatchFirst: '',
            ValorantLiveMatchSecond: '',
            ValorantUpcomingMatchFirst: '',
            ValorantUpcomingMatchSecond: '',
            ValorantFinishedMatchFirst: '',
            ValorantFinishedMatchSecond: '',
            DotaLiveMatchFirst: '',
            DotaLiveMatchSecond: '',
            DotaUpcomingMatchFirst: '',
            DotaUpcomingMatchSecond: '',
            DotaFinishedMatchFirst: '',
            DotaFinishedMatchSecond: '',
            LoLLiveMatchFirst: '',
            LoLLiveMatchSecond: '',
            LoLUpcomingMatchFirst: '',
            LoLUpcomingMatchSecond: '',
            LoLFinishedMatchFirst: '',
            LoLFinishedMatchSecond: '',
            r6LiveMatchFirst: '',
            r6LiveMatchSecond: '',
            r6UpcomingMatchFirst: '',
            r6UpcomingMatchSecond: '',
            r6FinishedMatchFirst: '',
            r6FinishedMatchSecond: '',
        },
        // forEditing: {
        //     CSLiveMatchFirst: '',
        //     CSLiveMatchSecond: '',
        //     CSUpcomingMatchFirst: '',
        //     CSUpcomingMatchSecond: '',
        //     CSFinishedMatchFirst: '',
        //     CSFinishedMatchSecond: '',
        //     ValorantLiveMatchFirst: '',
        //     ValorantLiveMatchSecond: '',
        //     ValorantUpcomingMatchFirst: '',
        //     ValorantUpcomingMatchSecond: '',
        //     ValorantFinishedMatchFirst: '',
        //     ValorantFinishedMatchSecond: '',
        //     DotaLiveMatchFirst: '',
        //     DotaLiveMatchSecond: '',
        //     DotaUpcomingMatchFirst: '',
        //     DotaUpcomingMatchSecond: '',
        //     DotaFinishedMatchFirst: '',
        //     DotaFinishedMatchSecond: '',
        //     LoLLiveMatchFirst: '',
        //     LoLLiveMatchSecond: '',
        //     LoLUpcomingMatchFirst: '',
        //     LoLUpcomingMatchSecond: '',  
        //     LoLFinishedMatchFirst: '',
        //     LoLFinishedMatchSecond: '',
        // r6LiveMatchFirst: '',  
        // r6LiveMatchSecond: '',
        // r6UpcomingMatchFirst: '',
        // r6UpcomingMatchSecond: '',
        // r6FinishedMatchFirst: '',
        // r6FinishedMatchSecond: '',
        // },
        pickem: {
            ShanghaiAmerican2024 : '/tournaments/perfect-world-shanghai-major-2024-american-rmb/pickems',
            ShanghaiAsia2024 : '/tournaments/perfect-world-shanghai-major-2024-asia-pacific-rmr/pickems',
            IESF2024 : '/tournaments/iesf-world-esports-championship-2024/pickems',
            ShanghaiEuropeA2024 : '/tournaments/perfect-world-shanghai-major-2024-european-rmb-a/pickems',
            ShanghaiEuropeB2024 : '/tournaments/perfect-world-shanghai-major-2024-european-rmb-b/pickems',
        },
        userGroup: {
            joinPickemShanghaiAmerican2024 : '/tournaments/perfect-world-shanghai-major-2024-american-rmb/pickems?user_group_code=8844353565',
            joinPickemShanghaiAsia2024 : '/tournaments/perfect-world-shanghai-major-2024-asia-pacific-rmr/pickems?user_group_code=7318327886',
            joinPickemIESF2024: '/tournaments/iesf-world-esports-championship-2024/pickems?user_group_code=1392988939',
            joinPickemShanghaiEuropeA2024: '/tournaments/perfect-world-shanghai-major-2024-european-rmb-a/pickems?user_group_code=5020834438',
            joinPickemShanghaiEuropeB2024: '/tournaments/perfect-world-shanghai-major-2024-european-rmb-b/pickems?user_group_code=7605220852',
        }
    },
    cs2: {
        ingame: {
            AdvancedFinishedMatch: '/matches/insanity-vs-oddik-19-09-2024/nuke',
            BasicFinishedMatch: '/matches/phoenix-vs-final-form-cs-20-09-2024',
            NoDataFinishedMatch: '/matches/sinners-vs-dynamo-eclot-20-09-2024',
            Bo1AdvancedFinishedMatch: '/matches/imperial-vs-oddik-06-09-2024/inferno',
            Bo1BasicFinishedMatch: '/matches/revenge-nation-vs-limitless-05-09-2024/anubis',
            Bo1NoDataFinishedMatch: '/matches/dynamo-eclot-vs-brute-05-09-2024',
            BasicMap: '/matches/incontrol-vs-detonate-21-09-2024/ancient',
            AdvancedMap: '/matches/permitta-vs-ecstatic-21-09-2024/ancient',
            Round: '/matches/eyeballers-vs-nexus-19-09-2024/nuke/round-29',
            Performance: '/matches/lag-gaming-vs-legacy-br-20-09-2024/dust2/performance',
            Aim: '/matches/natus-vincere-junior-vs-spirit-academy-21-09-2024/aim',
            Granades: '/matches/eyeballers-vs-k27-21-09-2024/grenades',
            Devices: '/matches/gaimingladiators-vs-kono-ecf-21-09-2024/devices',
            Economy: '/matches/rhyno-vs-quazar-21-09-2024/economy',
            RoundPerformance: '/matches/9-pandas-vs-copenhagen-wolves-19-09-2024/anubis/round-30/performance',
            RoundAim: '/matches/zero-tenacity-vs-favbet-19-09-2024/nuke/round-18/aim',
            RoundGranades: '/matches/9ine-vs-sinners-19-09-2024/nuke/round-30/grenades',
            RoundDevices: '/matches/sashi-esport-vs-monte-19-09-2024/nuke/round-30/devices',
            RoundEconomy: '/matches/johnny-speeds-vs-alliance-cs-19-09-2024/ancient/round-24/economy',
        },
        profiles: {
            TournamentOverview: '/tournaments/esl-pro-league-season-20',
            TournamentStages: '/tournaments/galaxy-battle-1#tab-stages',
            TournamentPickems: '/tournaments/iem-cologne-2024/pickems',
            TournamentResults: '/tournaments/esl-challengel-asia-48/results',
            TournamentMatches: '/tournaments/cct-season-2-european-series-14/matches',
            TournamentTeams: '/tournaments/yalla-compass-summer-2024#tab-teams',
            TournamentStats: '/tournaments/esports-world-cup-2024#tab-stats',
            PlayerOverview: '/players/zywoo',
            PlayerCareer: '/players/r1nkle#tab-career',
            PlayerMatches: '/players/jl-cs-go/matches',
            PlayerTournaments: '/players/b1t/tournaments',
            PlayerStats: '/players/w0nderful#tab-stats',
            TeamOverview: '/teams/natus-vincere',
            TeamSquad: '/teams/b8#tab-squad',
            TeamMatches: '/teams/monte/matches',
            TeamTournaments: '/teams/passion-ua/tournaments',
            TeamStats: '/teams/kono-ecf#tab-stats',
            InsideNews: '/news/dlsm-partners-blast-world-final-2024-singapore',
            InsideArticle: '/articles/best-cs2-charms',
            InsideWiki: '/wiki/butterfly-knife-stained',
            InsideForum: '/forum/pickem-esl-pro-league',
            InsidePredictions: '/predictions/spirit-vs-faze-match-prediction-and-analysis-perfect-world-shanghai-major-2024-grand-final',
            TeamsCompareInserted: '/tools/compare/teams?metrics=main,performance,aim,economy,grenades,primary_devices,pistols,multikills,clutches&period=last_6_months&slugs=natus-vincere,monte,passion-ua',
            PlayersCompareInserted: '/tools/compare/players?metrics=main,performance,aim,economy,grenades,primary_devices,pistols,multikills,clutches&period=last_6_months&slugs=jl-cs-go,b1t,somedieyoung',
            Pickem: '/tournaments/iem-cologne-2024/pickems',
            UserOverview: '/users/3515',
            UserComments: '/users/422/comments',
            UserPickems: '/users/2172/pickems',
            UserPickemInTournament: '/tournaments/iem-dallas-2024/pickems?user_id=4992',
            PremiumSubscription: '/premium',
            WikiHelpUkraine: '/wiki/help-ukraine',
            WikiPrivacy: '/wiki/privacy-policy',
            CCTOverview: '/series/champion-of-champions-tour?dark=true',
            CCTResults: '/series/champion-of-champions-tour/results',
            CCTMatches: '/series/champion-of-champions-tour/matches',
            CCTTeams: '/series/champion-of-champions-tour/teams',
            CCTPlayers: '/series/champion-of-champions-tour/players',
            AllPlayersMain: '/players?period=all_time&tiers=s,a&tab=main&sort=rating&order=desc',
            AllPlayersPerformance: '/players?period=all_time&tiers=s,a&tab=performance&sort=open_kills&order=desc&map_name=de_anubis&map_id=27',
            AllPlayersAim: '/players?period=all_time&tiers=&tab=aim&sort=headshots&order=desc&country_id=58&country_name=Ukraine&games_count=60',
            AllPlayersGrenades: '/players?period=all_time&tiers=&tab=grenades&sort=flash_assist&order=desc&games_count=60&team_slug=natus-vincere&team_id=787',
            AllPlayersPrimaryDevices: '/players?period=all_time&tiers=s&tab=primary_devices&sort=ak47_kills&order=desc&games_count=60',
            AllPlayersPistols: '/players?period=all_time&tiers=s&tab=pistols&sort=deagle_kills&order=desc&games_count=60&team_side=CT',
            AllPlayersEconomy: '/players?period=all_time&tiers=s&tab=economy&sort=kill_cost&order=desc&games_count=35',
            AllPlayersMultikills: '/players?period=all_time&tiers=&tab=multikills&sort=multikills_vs_5&order=desc&games_count=35',
            AllPlayersClutches: '/players?period=all_time&tiers=&tab=clutches&sort=clutches_vs_5&order=desc&games_count=35',
            PlayerMaps: '/players/twistzz/maps',
            CoachOverview: '/coaches/b1ad3#tab-overview',
            CoachCareer: '/coaches/xtqzzz-cs-go#tab-career',
            CoachMatches: '/coaches/neo/matches',
            CoachTournaments: '/coaches/taz/tournaments',
            WikiCookie: '/wiki/cookie-policy',
            Author: '/authors/pers1valle',
        },
        menu: {
            HomePage: '/',
            UpcomingMatches: '/matches/current',
            FinishedMatches: '/matches/finished',
            UpcomingTournaments: '/tournaments/current',
            FinishedTournaments: '/tournaments/finished',
            Players: '/players',
            TeamEarnings: '/teams/earnings',
            TeamValveRanking: '/teams/valve-rankings/world',
            News: '/news',
            Articles: '/articles',
            Wiki: '/wiki/welcome',
            Forum: '/forum',
            Predictions: '/predictions',
            Records: '/records',
            CompareTeams: '/tools/compare/teams',
            ComparePlayers: '/tools/compare/players',
            Pickems: '/pickems',
        }
        
    },
    valorant: {
        ingame: {
            FullDataFinishedMatch: '/valorant/matches/all-knights-1-vs-galorys-18-09-2024',
            NoDataFinishedMatch: '/valorant/matches/all-knights-1-vs-m80-20-09-2024',
            Bo1FullDataFinishedMatch: '/valorant/matches/rtzn-vs-dsyre-29-06-2024/icebox',
            Bo1NoDataFinishedMatch: '/valorant/matches/spongebob-vs-lgbtq-09-07-2024',
            Performance: '/valorant/matches/disguised-vs-full-sense-21-09-2024/performance',
            Aim: '/valorant/matches/riddle-esports-vs-sin-prisa-gaming-21-09-2024/aim',
            Devices: '/valorant/matches/naos-esports-vs-boom-esports-20-09-2024/devices',
            Economy: '/valorant/matches/full-sense-vs-oblivion-force-20-09-2024/economy',
            RoundOverview: '/valorant/matches/mibr-female-vs-zeta-division-gc-14-11-2024/ascent',
            RoundPerformance: '/valorant/matches/m80-vs-2game-esports-18-09-2024/sunset/performance',
            RoundAim: '/valorant/matches/nasr-ignite-vs-karmine-corp-gc-17-09-2024/bind/aim',
            RoundDevices: '/valorant/matches/giantx-gc-vs-valiant-gc-17-09-2024/lotus/devices',
            RoundEconomy: '/valorant/matches/all-knights-1-vs-tsm-1-16-09-2024/sunset/economy',
        },
        profiles: {
            TournamentOverview: '/valorant/tournaments/vct-2024-game-changers-latin-america-south-mid-season',
            TournamentStages: '/valorant/tournaments/valorant-champions-tour-2024-masters-shanghai#tab-stages',
            TournamentResults: '/valorant/tournaments/valorant-champions-tour-2024-pacific-stage-1/results',
            TournamentMatches: '/valorant/tournaments/valorant-challengers-2024-spain-rising-consolidation/matches',
            TournamentTeams: '/valorant/tournaments/valorant-champions-tour-2024-americas-league-stage-1#tab-teams',
            PlayerOverview: '/valorant/players/3e-akai',
            PlayerCareer: '/valorant/players/srnfps#tab-career',
            PlayerMatches: '/valorant/players/zekken/matches',
            PlayerTournaments: '/valorant/players/lime/tournaments',
            TeamOverview: '/valorant/teams/geng-esports',
            TeamSquad: '/valorant/teams/sentinels#tab-squad',
            TeamMatches: '/valorant/teams/team-heretics/matches',
            TeamTournaments: '/valorant/teams/paper-rex-1/tournaments',
            InsideNews: '/valorant/news/the-valorant-console-community-is-interested-in-champions-collections-and-their-potential-future-appearance',
            InsideArticle: '/valorant/articles/ten-reasons-why-you-should-play-valorant',
            InsideForum: '/valorant/forum/yaka-komanda-naraz%d1%96-ye-top-1-v-sv%d1%96t%d1%96-1',
            InsidePredictions: '/valorant/predictions/players-we-havent-heard-of-could-really-surprise-us-pacific-2024-valorant-off-season-roster-results',
            InsidePickem: '/valorant/tournaments/valorant-champions-2024/pickems',
            CrosshairTopPlayers: '/valorant/crosshair/top-players',
            CrosshairPresets: '/valorant/crosshair/presets',
            PlayersPerformance: '/valorant/players?period=all_time&tab=performance&sort=open_kills&order=desc',
            PlayersAim: '/valorant/players?period=all_time&tab=aim&sort=body_shots_accuracy&order=desc',
            PlayersMultikills: '/valorant/players?period=all_time&tab=multikills&sort=m4_sum&order=desc',
            PlayersClutches: '/valorant/players?period=all_time&tab=clutches&sort=c3_sum&order=desc',
            PlayersEconomy: '/valorant/players?period=all_time&tab=economy&sort=kill_cost&order=asc',
            CoachOverview: '/valorant/coaches/effys-loic-sauvageau#tab-overview',
            CoachCareer: '/valorant/coaches/muggle#tab-career',
            CoachMatches: '/valorant/coaches/neilzinho-vlr/matches',
            CoachTournaments: '/valorant/coaches/itopata/tournaments',
        },
        menu: {
            HomePage: '/valorant',
            UpcomingMatches: '/valorant/matches/current',
            FinishedMatches: '/valorant/matches/finished',
            UpcomingTournaments: '/valorant/tournaments/current',
            FinishedTournaments: '/valorant/tournaments/finished',
            Players: '/valorant/players',
            TeamEarnings: '/valorant/teams/earnings',
            News: '/valorant/news',
            Articles: '/valorant/articles',
            Forum: '/valorant/forum',
            Predictions: '/valorant/predictions',
            Pickems: '/valorant/pickems',
            Crosshairs: '/valorant/crosshair/generator',
        }
    },
    dota: {
        ingame: {
            FullDataFinishedMatch: '/dota2/matches/tt-infinbank-vs-avulus-16-09-2024',
            NoDataFinishedMatch: '/dota2/matches/numa-numa-lei-vs-vicious-gaming-11-11-2024',
            Map: '/dota2/matches/1win-1-vs-avulus-30-08-2024/map-5',
            NoDataFinishedMap: '/dota2/matches/numa-numa-lei-vs-vicious-gaming-11-11-2024/map-1',
        },
        profiles: {
            TournamentOverview: '/dota2/tournaments/the-international-2024',
            TournamentStages: '/dota2/tournaments/dreamleague-season-25#tab-stages',
            TournamentResults: '/dota2/tournaments/fissure-universe-episode-3-2024/results',
            TournamentMatches: '/dota2/tournaments/european-pro-league-season-20/matches',
            TournamentTeams: '/dota2/tournaments/elite-league-season-2-2024#tab-teams',
            PlayerOverview: '/dota2/players/33-neta-shapira',
            PlayerMatches: '/dota2/players/benren/matches',
            PlayerTournaments: '/dota2/players/mikoto/tournaments',
            TeamOverview: '/dota2/teams/team-liquid-dota2',
            TeamSquad: '/dota2/teams/execration#tab-squad',
            TeamMatches: '/dota2/teams/nouns-dota2/matches',
            TeamTournaments: '/dota2/teams/mouz-dota2/tournaments',
            InsideNews: '/dota2/news/pgl-wallachia-season-2-kicks-off',
            InsideArticle: '/dota2/articles/13-facts-about-team-liquid-ti13-champion',
            InsidePredictions: '/dota2/predictions/pari-vs-bb-match-prediction-at-esl-one-bangkok-2024',
            CoachOverview: '/dota2/coaches/blitz-dota#tab-overview',
            CoachCareer: '/dota2/coaches/cy-#tab-career',
            CoachMatches: '/dota2/coaches/aui_2000/matches',
            CoachTournaments: '/dota2/coaches/moonmeander/tournaments',
        },
        menu: {
            HomePage: '/dota2',
            UpcomingMatches: '/dota2/matches/current',
            FinishedMatches: '/dota2/matches/finished',
            UpcomingTournaments: '/dota2/tournaments/current',
            FinishedTournaments: '/dota2/tournaments/finished',
            Players: '/dota2/players',
            TeamEarnings: '/dota2/teams/earnings',
            News: '/dota2/news',
            Articles: '/dota2/articles',
            Predictions: '/dota2/predictions',
            Heroes: '/dota2/heroes',
        }
    },
    lol: {
        ingame: {
            FullDataFinishedMatch: '/lol/matches/lua-gaming-lol-vs-barca-esports-lol-12-11-2024',
            NoDataFinishedMatch: '/lol/matches/big-green-mood-vs-all-i-want-15-11-2024',
            Map: '/lol/matches/karmine-corp-blue-vs-vitalitybee-30-09-2024/map-1',
            NoDataFinishedMap: '/lol/matches/big-green-mood-vs-all-i-want-15-11-2024/map-1',
        },
        profiles: {
            TournamentOverview: '/lol/tournaments/worlds-2023',
            TournamentStages: '/lol/tournaments/lec-winter-2025#tab-stages',
            TournamentResults: '/lol/tournaments/lck-summer-2024/results',
            TournamentMatches: '/lol/tournaments/worlds-2024/matches',
            TournamentTeams: '/lol/tournaments/worlds-2023#tab-teams',
            PlayerOverview: '/lol/players/rhilech',
            PlayerMatches: '/lol/players/myrwn/matches',
            PlayerTournaments: '/lol/players/busio/tournaments',
            TeamOverview: '/dota2/teams/team-liquid-dota2',
            TeamSquad: '/dota2/teams/execration#tab-squad',
            TeamMatches: '/dota2/teams/nouns-dota2/matches',
            TeamTournaments: '/dota2/teams/mouz-dota2/tournaments',
            InsideNews: '/lol/news/pro-players-at-bootcamps-in-europe-ahead-of-worlds',
            InsideArticle: '/lol/articles/kaisa-the-daughter-of-the-void-season-14-guide',
            InsideForum: '/lol/forum/how-many-champions-are-free-in-league-of-legends',
            InsidePredictions: '/lol/predictions/worlds-2024-finals-t1-vs-blg-prediction',
            CoachOverview: '/lol/coaches/kkoma#tab-overview',
            CoachCareer: '/lol/coaches/bigwei#tab-career',
            CoachMatches: '/lol/coaches/chieh/matches',
            CoachTournaments: '/lol/coaches/tselin/tournaments',
            PlayerCareer: '/lol/players/doinb#tab-career',
        },
        menu: {
            HomePage: '/lol',
            UpcomingMatches: '/lol/matches/current',
            FinishedMatches: '/lol/matches/finished',
            UpcomingTournaments: '/lol/tournaments/current',
            FinishedTournaments: '/lol/tournaments/finished',
            Players: '/lol/players',
            TeamEarnings: '/lol/teams/earnings',
            News: '/lol/news',
            Articles: '/lol/articles',
            Forum: '/lol/forum',
            Predictions: '/lol/predictions',
            Champions: '/lol/champions'
        }
    },
    games: {
        HomePage: '/games',
        News: '/games/news',
        Articles: '/games/articles',
        Forum: '/games/forum',
        InsideNews: '/games/news/the-all-ukrainian-heartstone-tournament-from-blackbears-has-been-announced',
        InsideArticle: '/games/articles/best-single-player-pc-games',
        InsideForum: '/games/forum/i-feel-like-bo6-is-the-best-cod-like-ever-if-not-consider-nostalgia',
    },
    r6: {
        ingame: {
            FullDataFinishedMatch: '/r6siege/matches/oxygen-esports-1-vs-team-cruelty-2-13-01-2025',
            NoDataFinishedMatch: '/r6siege/matches/fnatic-2-vs-into-the-breach-1-26-01-2025',
            Map: '/r6siege/matches/wildcard-gaming-2-vs-oxygen-esports-1-13-01-2025/bank',
            NoDataFinishedMap: '/r6siege/matches/ence-1-vs-wolves-esports-1-27-01-2025-1',
        },
        menu: {
            HomePage: '/r6siege',
            UpcomingMatches: '/r6siege/matches/current',
            FinishedMatches: '/r6siege/matches/finished',
            UpcomingTournaments: '/r6siege/tournaments/current',
            FinishedTournaments: '/r6siege/tournaments/finished',
            News: '/r6siege/news',
            Articles: '/r6siege/articles',
            Forum: '/r6siege/forum',
            Predictions: '/r6siege/predictions',
        },
        profiles: {
            TournamentOverview: '/r6siege/tournaments/six-invitational-2025',
            TournamentStages: '/r6siege/tournaments/blast-r6-major-montreal-2024#tab-stages',
            TournamentResults: '/r6siege/tournaments/six-invitational-north-america-finals-2025/results',
            TournamentMatches: '/r6siege/tournaments/malta-cyber-series-viii/matches',
            TournamentTeams: '/r6siege/tournaments/br-premier-2024#tab-teams',
            PlayerOverview: '/r6siege/players/rider-c8967ce6-674d-4b5e-b9af-7743adb73322',
            PlayerMatches: '/r6siege/players/reeps96/matches',
            PlayerTournaments: '/r6siege/players/peres/tournaments',
            TeamOverview: '/r6siege/teams/falcons-esport-1',
            TeamSquad: '/r6siege/teams/team-liquid-1#tab-squad',
            TeamMatches: '/r6siege/teams/darkzero-esports-1/matches',
            TeamTournaments: '/r6siege/teams/m80-1/tournaments',
            InsideNews: '/r6siege/news/ubisoft-has-released-a-teaser-for-the-assault-on-hereford-event-for-rainbow-six-siege',
            InsideArticle: '/r6siege/articles/rainbow-six-siege-how-to-level-up-fast',
            InsidePredictions: '/r6siege/predictions/ssg-vs-w7m-match-prediction-and-analysis-six-invitational-2025-group-stage',
            CoachOverview: '/r6siege/coaches/rafadell#tab-overview',
            CoachMatches: '/r6siege/coaches/supr/matches',
            CoachTournaments: '/r6siege/coaches/igoorctg/tournaments',
            InsideForum: '/r6siege/forum/am-i-the-only-one-who-bought-this-game-and-never-launched-it',
        },
    }
}